###
GET http://localhost:3001/status

###
GET http://localhost:3001/logout


###

POST http://localhost:3001/login
content-type: application/json

{
    "username": "sonntag",
    "password": "sonntag"
}

###

POST http://localhost:3001/register
content-type: application/json

{
    "username": "sonntag",
    "password": "sonntag"
}

###
GET http://localhost:3001/ai


###
GET http://localhost:3001/ai/s


###
GET http://localhost:3001/ai/models

###

POST http://localhost:3001/ai/completion
content-type: application/json

{
    "question": "Wie funktioniert ein E-Motor?"

}



###

POST http://localhost:3001/ai/correctText
content-type: application/json

{
    "input": "What day of the wek is tody?"

}


POST http://localhost:3001/ai/image
content-type: application/json

{
    "imageDescript": "christmas tree"


}

